/** Declaration file generated by dts-gen */

export = ytdl_core;

declare function ytdl_core(link: any, options: any): any;

declare namespace ytdl_core {
    const cache: {
        cookie: Map<any, any>;
        info: Map<any, any>;
        sig: Map<any, any>;
    };

    function chooseFormat(formats: any, options: any): any;

    function downloadFromInfo(info: any, options: any): any;

    function filterFormats(formats: any, filter: any): any;

    function getBasicInfo(link: any, options: any, callback: any): any;

    function getInfo(link: any, options: any, callback: any): any;

    function getURLVideoID(link: any): any;

    function getVideoID(str: any): any;

    function validateID(id: any): void;

    function validateURL(string: any): any;

}

